# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d362ca7e01b218ec228e2548acb9e4487bdd6bf8e46c0bef2846ef7ed204beca503765b4f2ccbd12de0e9b97e9ea16d810b0333d26120ec51bf5e1b7ef244dc9

test:
  secret_key_base: f05333fda0aa820b46015ee2126ef3d6a9f516c7f9d9666c514728784b114e8085014822632f88e700f1b9d6987b1700f5ec6f5a0172d7a549329d29dca70c15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
